name: On each commit push

on: push

jobs:
  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Docker Lint
        uses: luke142367/Docker-Lint-Action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        if: github.actor == 'ChristophShyper'
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          TERM: xterm-256color
        run: make build

  pull_requests:
    name: Create Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Create pull request - enhancement (conditional)
        if: startsWith(github.ref, 'refs/heads/enhancement')
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "auto,enhancement"
          pr_body: "*Automated pull request*"
          pr_title: "${{ github.event.commits[0].message }}"
          pr_reviewer: ChristophShyper
          pr_assignee: ChristophShyper

      - name: Create pull request - documentation (conditional)
        if: startsWith(github.ref, 'refs/heads/documentation')
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "auto,documentation"
          pr_body: "*Automated pull request*"
          pr_title: "${{ github.event.commits[0].message }}"
          pr_reviewer: ChristophShyper
          pr_assignee: ChristophShyper

      - name: Create pull request - other (conditional)
        if: github.ref != 'refs/heads/master' && startsWith(github.ref, '!refs/heads/documentation') && startsWith(github.ref, '!refs/heads/enhancement')
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "auto"
          pr_body: "*Automated pull request*"
          pr_title: "${{ github.event.commits[0].message }}"
          pr_reviewer: ChristophShyper
          pr_assignee: ChristophShyper
